# Generated by Django 5.0.6 on 2024-05-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-vector%2Fno-image-available&psig=AOvVaw2r13POnLA41FZgsD0myA6S&ust=1715992028754000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCLiqhM62k4YDFQAAAAAdAAAAABAE",
                max_length=200,
            ),
        ),
    ]
