# Generated by Django 5.0.6 on 2024-05-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
