# Generated by Django 5.0.6 on 2024-05-17 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0003_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
