# Generated by Django 5.0.6 on 2024-05-17 00:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0005_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
