# Generated by Django 4.1 on 2024-05-18 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_orderedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='product_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
