# Generated by Django 5.0.6 on 2024-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0009_remove_orderedproduct_product_orderedproduct_cart_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
    ]
