# Generated by Django 5.0.6 on 2024-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eshop", "0010_cart_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
