# Generated by Django 5.0.6 on 2024-05-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0002_rename_customuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
