# Generated by Django 4.1 on 2024-05-19 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0005_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='username',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
